name: test
channels:
  - conda-forge
  - defaults
dependencies:
  # obspy
  - decorator
  - lxml
  - matplotlib
  - numpy
  # see #3330 and SciTools/cartopy#2199
  # unpin again later on when this is fixed
  - scipy < 1.11
  - requests
  - setuptools
  # see #3258
  - sqlalchemy < 2.0
  # tests
  - pytest
  - pytest-cov
  - pytest-json-report >= 1.4
