name: "docs"
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  push:
    branches:
      - master
    tags-ignore:
      - '**'
  release:
    types: [published]

# cancel previous runs, but only in PRs, do not cancel previous runs if this run will be skipped
concurrency:
  group: docs-${{ github.event.pull_request.number || github.run_id }}-${{ !((github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'build_docs')) || github.event.label.name == 'build_docs') || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    # only run if on master branch OR if PR is updated and build_docs label present OR if build_docs_label is added
    if: github.event_name != 'pull_request' || ((github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'build_docs')) || github.event.label.name == 'build_docs')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: 'latest'
          python-version: '3.9'
          activate-environment: obspydoc
          environment-file: .github/docs_conda_env.yml
      - name: install obspy
        shell: bash -l {0}
        run: |
          python -m pip install .
      - name: build doc
        shell: bash -l {0}
        run: |
          cd misc/docs
          make html
      - name: build docset
        shell: bash -l {0}
        run: |
          cd misc/docs/build
          python -c 'import obspy; print(obspy.__version__)'
          echo "DOCSETVERSION=$(head -3 html/objects.inv | grep ' ObsPy Documentation ' | sed 's#.*(\(.*\)).*#\1#')" >> "$GITHUB_ENV"
          ls -l *
          ls -l */*
          doc2dash --verbose --name "ObsPy ${DOCSETVERSION}" --icon html/_static/obspy-logo_32x32.png --online-redirect-url https://docs.obspy.org/ html/
          ls -l *
          sed 's#\(<string>[Oo]bs[Pp]y\) .*\(</string>\)#\1 ${DOCSETVERSION}\2#' --in-place "ObsPy $(DOCSETVERSION).docset/Contents/Info.plist"
          cat ../docset_css_fixes.css >> "ObsPy ${DOCSETVERSION}.docset/Contents/Resources/Documents/_static/css/custom.css"
          tar --exclude='.DS_Store' -cvzf "obspy-${DOCSETVERSION}.docset.tgz" "ObsPy ${DOCSETVERSION}.docset"
      - name: compress with tar
        shell: bash -l {0}
        run: |
          cd misc/docs/build/html/
          tar cfJ obspydoc.tar.xz *
      - uses: actions/upload-artifact@v4
        with:
          name: obspydoc
          path: misc/docs/build/html/obspydoc.tar.xz
      - uses: actions/upload-artifact@v4
        with:
          name: obspydocset
          path: misc/docs/build/obspy-*.docset.tgz
